### ISSUE TITLE
Code is not documented or PEP8 compliant

### ISSUE THREAD

**Issue by mo-g** [mo-g/1910calleditwantsitsphoneback#9]
Imported code is not PEP8 compliant. It should be checked and fixed with pylint and pep8. In-line documentation should also be populated.

@dkillick I was thinking of you. :thinking:

**Comment by DPeterK** [comment]
@mo-g don't make me come over there and enforce pep8 compliance on you!

**Comment by mo-g** [comment]
@dkillick I've created tests for my new abstraction of `threading.Timer()` and both the module and the tests are pep8 and pylint approved! ;)

**Comment by mo-g** [comment]
So, I've had to rewrite most of the code to fix up the non-pythonic stuff and give a cleaner interface between classes. it means that most of the code that makes it work has been replaced with stubs and prototypes, but they are pretty much pep8 compliant out of the box. that said, I haven't touched sipclient or webserver, and most of the rest of my code isn't merged yet - so this stays open for now.

**Comment by DPeterK** [comment]
I feel like the scope of this issue is snowballing some... :snowman_with_snow:

**Comment by mo-g** [comment]
Nice emoji use.

I'm not rewriting the whole codebase as a result of fixing PEP8 compliance. I rewrote the whole codebase ANYWAY, and that's had the positive side-effect of everything is now PEP8 compliant.

Well.

Everything that's left.

**Comment by mo-g** [comment]
It's not perfect, but all modules are now mostly compliant. Continuing to fix as I go, but I'm happy with calling this 'good enough'.

Advantages of working on a personal project with no other developers in my own time. ;)

**Comment by DPeterK** [comment]
>  I'm happy with calling this 'good enough'

A good way to be!

> Advantages of working on a personal project with no other developers in my own time

A laudable goal with almost no downsides whatsoever...

**Comment by mo-g** [comment]
Except the lack of peer review, workload sharing, communal discussion of design, positive reinforcement of work ethic and design standards, pay... ;)
